### ISSUE TITLE
WORKFLOW MODELER BASELINE

### ISSUE THREAD

**Issue by wederbn** [SeQuenC-Consortium/workflow-modeler#7]
## Features

- [x] Initial Reading: 
  - [x] Familiarize yourself with the concept of [workflows](https://camunda.com/de/bpmn/)
  - [x] Familiarize yourself with the Workflow Modeler [documentation](https://github.com/SeQuenC-Consortium/workflow-modeler/tree/master/doc)
  - [x] Explore the following [example use case](https://github.com/UST-QuAntiL/QuantME-UseCases/tree/master/2021-edoc) to get familiar with the modeler functionalities. Instead of the QuantME Transformation Framework, use the workflow modeler available in this repository
- [x] As an initial issue, start working on #6 

Estimated Story Points 23-05-10: 5

**Comment by PatrickEbner** [comment]
Documentation in Confluence
